import os
import sys
import subprocess
import shutil
from termcolor import colored
import platform
import textwrap

DEVELOPER = "zerosocialcode"
TOOL_NAME = "SCARFACE FRAMEWORK"

MODULE_DESCRIPTIONS = {
    "harvest":  "Phishing Server & Tunneling Listener",
    "mailbird": "Automated Campaign Delivery System",
    "mailroom": "Social Engineering Lure Builder",
    "cloner":   "Target Website Replication Utility"
}

MODULE_DETAILS = {
    "harvest": {
        "role": "Listener & Credential Capture",
        "info": (
            "Hosts cloned websites locally and exposes them to the public internet using "
            "secure tunnels (Cloudflared, Ngrok, LocalTunnel). It injects JS/PHP loggers "
            "into the target site to intercept login attempts in real-time."
        ),
        "usage": "Select a cloned site -> Choose Port -> Select Tunnel -> Monitor Live Logs."
    },
    "cloner": {
        "role": "Reconnaissance & Mirroring",
        "info": (
            "A recursive website scraper that replicates target web pages with high fidelity. "
            "It automatically downloads assets (CSS, JS, Images) and rewrites paths to ensure "
            "the site renders perfectly offline. Includes meta-tag injection for mobile responsiveness."
        ),
        "usage": "Enter Target URL -> Set Depth -> Save."
    },
    "mailroom": {
        "role": "Payload & Template Generation",
        "info": (
            "An advanced HTML builder for creating convincing email lures. It allows you to "
            "embed the malicious links generated by the Harvest module into professional-looking "
            "email templates (e.g., Security Alerts, Password Resets)."
        ),
        "usage": "Select Template -> Customize Fields -> Export HTML."
    },
    "mailbird": {
        "role": "Delivery & Execution",
        "info": (
            "A mass-mailing utility designed to deliver payloads to target inboxes. Supports "
            "HTML body injection, custom SMTP servers, and bulk recipient lists. It closes the "
            "attack loop by delivering the 'Mailroom' templates to the victim."
        ),
        "usage": "Set SMTP Config -> Load List -> Select Template -> Launch Campaign."
    }
}

def get_terminal_width():
    try:
        return shutil.get_terminal_size().columns
    except (OSError, AttributeError):
        return 80

def clear_screen():
    os.system('cls' if platform.system() == 'Windows' else 'clear')

def print_centered(text, width, color='white', attrs=None):
    if attrs is None: attrs = []
    padding = max(0, (width - len(text)) // 2)
    print(" " * padding + colored(text, color, attrs=attrs))

def count_templates(root_path):
    template_dir = os.path.join(root_path, 'data', 'email_templates')
    if not os.path.exists(template_dir):
        return 0
    try:
        return len([f for f in os.listdir(template_dir) if f.endswith('.html')])
    except OSError:
        return 0

def count_cloned_sites(root_path):
    sites_dir = os.path.join(root_path, 'data', 'sites')
    if not os.path.exists(sites_dir):
        return 0
    try:
        return len([d for d in os.listdir(sites_dir) if os.path.isdir(os.path.join(sites_dir, d))])
    except OSError:
        return 0

def print_header(module_count, template_count, site_count):
    width = get_terminal_width()
    
    print("\n")
    print_centered(TOOL_NAME, width, 'white', ['bold'])
    
    dev_text = f"developer: {DEVELOPER}"
    print_centered(dev_text, width, 'blue')
    
    stats_text = f"Modules: {module_count}   |   Templates: {template_count}   |   Clones: {site_count}"
    print_centered(stats_text, width, 'cyan')
    
    print() 
    
    print("\n")

def scan_tools(base_path):
    found_tools = {}
    if not os.path.exists(base_path):
        return found_tools

    for entry in os.listdir(base_path):
        tool_path = os.path.join(base_path, entry)
        if os.path.isdir(tool_path):
            for main_file in ["main.py", "__main__.py"]:
                if os.path.isfile(os.path.join(tool_path, main_file)):
                    found_tools[entry.lower()] = os.path.join(tool_path, main_file)
                    break
    return found_tools

def print_menu(tools_map):
    width = get_terminal_width()
    preferred_order = ["harvest", "mailbird", "mailroom", "cloner"]
    
    display_lines = []
    
    for key in preferred_order:
        if key in tools_map:
            name = MODULE_DESCRIPTIONS.get(key, key.capitalize())
            display_lines.append(name)
            
    for key in tools_map:
        if key not in preferred_order:
            display_lines.append(key.capitalize())
            
    display_lines.append("Close")

    if display_lines:
        max_len = max(len(line) for line in display_lines)
    else:
        max_len = 10
        
    indent = max(0, (width - max_len) // 2)
    margin = " " * indent

    for line in display_lines:
        if line == "Close":
            print()
            print(f"{margin}{colored(line, 'white')}")
        else:
            print(f"{margin}{colored(line, 'cyan')}")
    
    print()

def print_help():
    width = get_terminal_width()
    print("\n")
    print_centered("SCARFACE FRAMEWORK DOCUMENTATION", width, 'white', ['bold'])
    print_centered("=" * 40, width, 'blue')
    print()
    
    preferred_order = ["harvest", "cloner", "mailroom", "mailbird"]
    
    content_width = min(width - 10, 80)
    indent = max(0, (width - content_width) // 2)
    margin = " " * indent
    
    for key in preferred_order:
        if key in MODULE_DETAILS:
            data = MODULE_DETAILS[key]
            
            header = f"COMMAND: {key.upper()}"
            print(f"{margin}{colored(header, 'green', attrs=['bold'])}")
            
            print(f"{margin}{colored('Role:', 'white')} {colored(data['role'], 'cyan')}")
            
            print(f"{margin}{colored('Description:', 'white')}")
            for line in textwrap.wrap(data['info'], width=content_width):
                print(f"{margin}  {colored(line, 'white', attrs=['dark'])}")
            
            print(f"{margin}{colored('Workflow:', 'white')} {colored(data['usage'], 'yellow')}")
            
            print(f"\n{margin}{colored('-' * content_width, 'blue')}\n")

    print_centered("Type any command above to launch the module.", width, 'white')
    print("\n")

def main():
    try:
        src_dir = os.path.dirname(os.path.abspath(__file__))
        root_path = os.path.dirname(src_dir)
        modules_path = os.path.join(src_dir, 'modules')
        
        while True:
            tools_map = scan_tools(modules_path)
            template_count = count_templates(root_path)
            site_count = count_cloned_sites(root_path)
            
            clear_screen()
            print_header(len(tools_map), template_count, site_count)
            
            if not tools_map:
                print_centered(f"No tools detected in {modules_path}", get_terminal_width(), 'red')
                sys.exit(1)
                
            print_menu(tools_map)
            
            prompt_text = colored("scarface> ", 'blue', attrs=['bold'])
            try:
                choice = input(prompt_text).strip()
            except EOFError:
                break
                
            if not choice:
                continue
                
            if choice.lower() == "help" or choice.lower() == "?":
                clear_screen()
                print_help()
                input(colored(f"\n{' ' * ((get_terminal_width()-26)//2)}Press Enter to return...", 'yellow'))
                continue

            if choice.lower() == "exit" or choice.lower() == "close":
                clear_screen()
                print_centered("Thank you for using Scarface Framework.", get_terminal_width(), 'red')
                sys.exit(0)
            
            selected_tool_path = None
            
            if choice.lower() in tools_map:
                selected_tool_path = tools_map[choice.lower()]
            
            if not selected_tool_path:
                for key, desc in MODULE_DESCRIPTIONS.items():
                    if choice.lower() == desc.lower():
                        if key in tools_map:
                            selected_tool_path = tools_map[key]
                            break

            if selected_tool_path:
                tool_dir = os.path.dirname(selected_tool_path)
                tool_script = os.path.basename(selected_tool_path)
                
                try:
                    subprocess.run([sys.executable, tool_script], cwd=tool_dir)
                except KeyboardInterrupt:
                    pass 
                except Exception as e:
                    print(colored(f"\nError running module: {e}", 'red'))
                    input("Press Enter to continue...")
            else:
                print(colored("\nUnknown command. Type 'help' for documentation.", 'red'))
                try:
                    input("Press Enter to continue...")
                except:
                    pass
                
    except KeyboardInterrupt:
        clear_screen()
        print_centered("Thank you for using Scarface Framework.", get_terminal_width(), 'red')
        sys.exit(0)

if __name__ == "__main__":
    main()
